import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";


const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets:["latin"]
})


export const metadata: Metadata = {
  title: "Admin Panel Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunitoSans.variable} antialiased bg-[#F5F6FA]`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >

        <Navbar/>
        <div className="w-[calc(100%-230px)] float-right h-[calc(100%-20rem)] px-10 pt-8 mt-16">
          
        {children}
        </div>
        <Sidebar/>
          </ThemeProvider>
      </body>
    </html>
  );
}
